{% set name = "Mastodon.py" %}
{% set version = "1.8.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "4a64cb94abadd6add73e4b8eafdb5c466048fa5f638284fd2189034104d4687e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner

  run:
    - python >=3.6
    - requests
    - python-dateutil
    - six
    - pytz
    - decorator >=4.0.0
    - http-ece >=1.0.5
    - cryptography >=1.6.0

test:
  imports:
    - mastodon

about:
  home: https://github.com/halcy/Mastodon.py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Python wrapper for the Mastodon API
  dev_url: https://github.com/halcy/Mastodon.py
  doc_url: https://mastodonpy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jsta
    - pmlandwehr
