{% set name = "Mastodon.py" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mastodon_py-{{ version }}.tar.gz
  sha256: 6602e9ca4db37c70b5adae5964d02e9a529f6cc8473947a314261008add208a5

build:
  number: 4
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - pytest-runner
    - python-magic

  run:
    - python >={{ python_min }}
    - requests >=2.4.2
    - python-dateutil
    - decorator >=4.0.0
    - blurhash >=1.1.4
    - python-magic

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - mastodon

about:
  home: https://github.com/halcy/Mastodon.py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Python wrapper for the Mastodon API
  dev_url: https://github.com/halcy/Mastodon.py
  doc_url: https://mastodonpy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jsta
    - pmlandwehr
