{% set name = "Mastodon.py" %}
{% set version = "2.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "ddab1cfd3e1d07e84dbca11cfde6c16128cccce8d8c69401cfc3def4265396cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mastodon_py-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner

  run:
    - python >={{ python_min }}
    - requests
    - python-dateutil
    - six
    - pytz
    - decorator >=4.0.0
    - http-ece >=1.0.5
    - cryptography >=1.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - mastodon

about:
  home: https://github.com/halcy/Mastodon.py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Python wrapper for the Mastodon API
  dev_url: https://github.com/halcy/Mastodon.py
  doc_url: https://mastodonpy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jsta
    - pmlandwehr
